In [1]:
import torch

##### Simple math operations

In [2]:
x = torch.linspace(0, 20, 11)
y = torch.rand(11)
print(x)
print()
print(y)

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18., 20.])

tensor([0.1307, 0.0613, 0.9313, 0.4704, 0.9958, 0.2775, 0.5421, 0.1703, 0.2486,
        0.4713, 0.6138])


In [3]:
torch.add(x, y)

tensor([ 0.1307,  2.0613,  4.9313,  6.4704,  8.9958, 10.2775, 12.5421, 14.1703,
        16.2486, 18.4713, 20.6138])

In [4]:
torch.mul(x, 3)

tensor([ 0.,  6., 12., 18., 24., 30., 36., 42., 48., 54., 60.])

In [5]:
torch.div(x, 2)

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [6]:
# Creates a new tensor with negative elements of the input.
torch.neg(x)

tensor([ -0.,  -2.,  -4.,  -6.,  -8., -10., -12., -14., -16., -18., -20.])

In [7]:
# Creates a tensor with element-wise power of the input.
torch.pow(x, 2)

tensor([  0.,   4.,  16.,  36.,  64., 100., 144., 196., 256., 324., 400.])

In [8]:
# Creates a tensor with element-wise square root of the input.
torch.sqrt(x)

tensor([0.0000, 1.4142, 2.0000, 2.4495, 2.8284, 3.1623, 3.4641, 3.7417, 4.0000,
        4.2426, 4.4721])

In [9]:
# Creates a tensor with element-wise reciprocal of the input.
torch.reciprocal(x)

tensor([   inf, 0.5000, 0.2500, 0.1667, 0.1250, 0.1000, 0.0833, 0.0714, 0.0625,
        0.0556, 0.0500])

In [10]:
torch.log10(y)

tensor([-0.8838, -1.2128, -0.0309, -0.3276, -0.0018, -0.5568, -0.2659, -0.7687,
        -0.6044, -0.3267, -0.2120])

###### Statistics

In [11]:
torch.mean(x)

tensor(10.)

In [12]:
torch.median(x)

tensor(10.)

In [13]:
torch.mode(x)

(tensor(0.), tensor(0))

In [14]:
torch.std(x)

tensor(6.6332)

In [15]:
torch.max(x)

tensor(20.)

In [16]:
torch.min(x)

tensor(0.)

##### Trigonometry

In [17]:
torch.sin(y)

tensor([0.1303, 0.0612, 0.8024, 0.4532, 0.8392, 0.2739, 0.5159, 0.1695, 0.2461,
        0.4541, 0.5760])

In [18]:
torch.cos(y)

tensor([0.9915, 0.9981, 0.5968, 0.8914, 0.5438, 0.9617, 0.8566, 0.9855, 0.9692,
        0.8910, 0.8175])

In [19]:
torch.tan(y)

tensor([0.1314, 0.0613, 1.3446, 0.5084, 1.5431, 0.2848, 0.6022, 0.1720, 0.2539,
        0.5096, 0.7046])