In [1]:
import torch

In [2]:
# Tensor of zeros.
torch.zeros(3, 7)

tensor([[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]])

In [3]:
# Tensor of ones.
torch.ones(5, 5)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [4]:
torch.full((3, 6), 5)

tensor([[5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5., 5.]])

In [5]:
# Creating an uninitialized tensor.
torch.empty(5, 7)

tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000]])

In [6]:
# Tensor filled with ones along the main diagonal and zeros as element off the main diagonal.
x = torch.eye(5)
print(x)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [7]:
# Creating tensor filled with zeros from an input.
torch.zeros_like(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [8]:
# Creating tensor filled with ones from an input.
torch.ones_like(x)

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [9]:
# Creating an uninitialized tensor from an input.
torch.empty_like(x)

tensor([[-1.2037e-10,  7.4409e-43,  7.9874e-44,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  4.7428e+30],
        [ 1.8754e+28,  3.2175e+21,  4.1025e-08,  1.2869e-11,  1.6986e+22],
        [ 8.3104e+20,  1.0720e-08,  1.0334e-05,  4.2770e-05,  8.4266e-07],
        [ 5.1436e-11,  4.2330e+21,  1.6534e+19,  3.0478e+32,  1.3563e-19]])

In [10]:
# Creates a tensor from an input with the same size as the input and filled with with a given fill value. 
torch.full_like(x, 2)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])

In [11]:
# Creates a tensor from an input with the same size as the input and is filled with random numbers from a uniform distribution. 
torch.rand_like(x)

tensor([[0.9575, 0.1991, 0.8334, 0.8794, 0.6924],
        [0.3243, 0.1124, 0.4532, 0.5346, 0.1176],
        [0.5169, 0.3945, 0.6750, 0.7869, 0.4200],
        [0.9891, 0.0567, 0.3442, 0.4817, 0.6950],
        [0.1177, 0.6923, 0.0671, 0.6331, 0.3649]])

In [12]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
y = torch.linspace(0, 20, steps=8)
y

tensor([ 0.0000,  2.8571,  5.7143,  8.5714, 11.4286, 14.2857, 17.1429, 20.0000])

In [14]:
torch.rand(3, 7)

tensor([[0.7950, 0.1080, 0.1298, 0.2343, 0.2796, 0.9007, 0.5273],
        [0.7334, 0.7358, 0.2971, 0.3511, 0.9719, 0.7155, 0.5042],
        [0.2470, 0.2748, 0.1293, 0.5390, 0.5680, 0.1737, 0.9706]])

In [15]:
y1 = torch.reshape(y, (2, 4))
y1

tensor([[ 0.0000,  2.8571,  5.7143,  8.5714],
        [11.4286, 14.2857, 17.1429, 20.0000]])

In [16]:
# Size of y1.
y1.size()

torch.Size([2, 4])

In [17]:
# Transpose
torch.t(y1)

tensor([[ 0.0000, 11.4286],
        [ 2.8571, 14.2857],
        [ 5.7143, 17.1429],
        [ 8.5714, 20.0000]])