In [1]:
import torch
import numpy as np

In [2]:
x = torch.full((4, 4), 3)
x

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])

In [3]:
# converting pytorch Tensor to numpy array.
y = x.numpy()
y

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)

In [4]:
# converting numpy array to pytorch Tensor.
z = torch.from_numpy(y)
z

tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])